.rubocop.yml:
  default_configs:
    Style/SignalException:
      Enabled: false
    Style/DoubleNegation:
      Enabled: false
    Style/MultipleComparison:
      Enabled: false
    Style/NumericPredicate:
      Enabled: false
    Layout/HeredocIndentation:
      Enabled: false
    Layout/LineLength:
      Enabled: false
    Metrics/BlockNesting:
      Enabled: false
    Naming/AccessorMethodName:
      Enabled: false
    Naming/PredicateName:
      Enabled: false
    RSpec/VariableName:
      Enabled: false
Gemfile:
  optional:
    ":development":
      - gem: beaker
        version: '~> 6.0'
        from_env: BEAKER_VERSION
      - gem: beaker-abs
        from_env: BEAKER_ABS_VERSION
        version: '~> 1.0'
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
        version: '~> 2'
      - gem: beaker-rspec
        from_env: BEAKER_RSPEC_VERSION
      - gem: beaker-puppet
        from_env: BEAKER_PUPPET_VERSION
        version: '~> 4.0'
      - gem: beaker-module_install_helper
      - gem: nokogiri
      # Conflicting Faraday requirements cause unexpected dependency resolution
      # Pin orchestrator_client until all dependencies support Faraday >= 2
      # See: P4DEVOPS-8804
      - gem: 'orchestrator_client'
        version: '< 0.7.1'
    ":system_tests":
      - gem: voxpupuli-acceptance

appveyor.yml:
  delete: true
.travis.yml:
  delete: true
.github/workflows/release.yml:
  unmanaged: false
.github/workflows/release_prep.yml:
  unmanaged: false
.gitlab-ci.yml:
  delete: true
# We still use the Vox acceptance Rake task instead of Litmus
Rakefile:
  requires:
    - require: voxpupuli/acceptance/rake
      conditional: Gem.loaded_specs.key? 'voxpupuli-acceptance'