---
name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Nightly:
    uses: "mhashizume/phoenix-github-actions/.github/workflows/unit_tests_with_nightly_puppet_gem.yaml@maint/main/bundler-cache"
  
  Released:
    uses: "mhashizume/phoenix-github-actions/.github/workflows/unit_tests_with_released_puppet_gem.yaml@maint/main/bundler-cache"
